name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm test -- --coverage --watchAll=false
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    

  detox-ios:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create development JS bundle
      run: npx expo export --dev --platform ios --clear
      
    - name: Run Expo prebuild
      run: npx expo prebuild --platform ios --npm
    
    - name: Setup Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods

    - name: Install applesimutils
      run: |
        brew tap wix/brew
        brew install applesimutils
    
    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install --deployment
    
    - name: Boot iOS Simulator
      run: |
        xcrun simctl boot "iPhone 15" || true
        xcrun simctl bootstatus "iPhone 15" -b
        
    - name: Build Detox for iOS
      run: |
        export NODE_ENV=development
        npx detox build --configuration ios.sim.debug
    
    - name: Run Detox tests on iOS
      run: npx detox test --configuration ios.sim.debug --cleanup --headless --loglevel verbose